Models/UserViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Linq;

namespace GymWebApp.Models {

    public class EditUserViewModel {
        [Required]
        public string ID { get; set; }

        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        public int ProfileId { get; set; }

        [Required]
        public string FirstName { get; set; }

        [Required]
        public string LastName { get; set; }

        public byte[] Avatar { get; set; }
    }
}

Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GymWebApp.Models;
using System.Data.Entity.Infrastructure;

namespace GymWebApp.Controllers
{
    public class UsersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [Authorize(Roles = "ADMIN")]
        public ActionResult Index()
        {
            ViewData["Phrase"] = "";
            string roleId = db.Roles.First(role => role.Name == "CLIENT").Id;
            return View(db.Users.Where(user => user.Roles.Any(r => r.RoleId == roleId)));
        }

        [Authorize(Roles = "ADMIN")]
        public ActionResult Search(string phrase) {
            ViewData["Phrase"] = phrase;
            string roleId = db.Roles.First(role => role.Name == "CLIENT").Id;
            return View("Index", db.Users.Where(user => user.Roles.Any(r => r.RoleId == roleId) && user.Email.Contains(phrase)));
        }

        [Authorize(Roles = "ADMIN")]
        public ActionResult Details(string id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser user = db.Users.Find(id);
            if (user == null) {
                return HttpNotFound();
            }
            return View(user);
        }

        [Authorize(Roles = "ADMIN")]
        public ActionResult Edit(string id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser user = db.Users.Find(id);
            if (user == null) {
                return HttpNotFound();
            }
            return View(new EditUserViewModel { ID=user.Id, Email=user.Email, ProfileId=user.MyProfile.ID, FirstName = user.MyProfile.FirstName, LastName = user.MyProfile.LastName });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMIN")]
        public ActionResult Edit(EditUserViewModel m, HttpPostedFileBase upload) {
            ApplicationUser userToUpdate = db.Users.Find(m.ID);
            userToUpdate.Email = m.Email;
            userToUpdate.UserName = m.Email;

            Profile profileToUpdate = userToUpdate.MyProfile;
            profileToUpdate.FirstName = m.FirstName;
            profileToUpdate.LastName = m.LastName;
            try {
                if (ModelState.IsValid) {
                    if (upload != null && upload.ContentLength > 0) {
                        using (var reader = new System.IO.BinaryReader(upload.InputStream)) {
                            profileToUpdate.Avatar = reader.ReadBytes(upload.ContentLength);
                            profileToUpdate.Type = upload.ContentType;
                        }
                    }
                    db.Entry(userToUpdate).State = EntityState.Modified;
                    db.Entry(profileToUpdate).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Details", new { id = m.ID });
                }
            }
            catch (RetryLimitExceededException) {
                ModelState.AddModelError("", "Unable to save changes.");
            }
            return View("Edit", new { id = m.ID });
        }

        //// GET: Users/Delete/5
        //public ActionResult Delete(string id) {
        //    if (id == null) {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    ApplicationUser applicationUser = db.ApplicationUsers.Find(id);
        //    if (applicationUser == null) {
        //        return HttpNotFound();
        //    }
        //    return View(applicationUser);
        //}

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(string id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser user = db.Users.Find(id);
            if (user == null) {
                return HttpNotFound();
            }

            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing) {
            if (disposing) {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Users/Delete.cshtml
@model GymWebApp.Models.ApplicationUser

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ApplicationUser</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MyProfile.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MyProfile.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailConfirmed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailConfirmed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PasswordHash)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PasswordHash)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecurityStamp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecurityStamp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumberConfirmed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumberConfirmed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TwoFactorEnabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TwoFactorEnabled)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LockoutEndDateUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LockoutEndDateUtc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LockoutEnabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LockoutEnabled)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccessFailedCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccessFailedCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Users/Details.cshtml
@model GymWebApp.Models.ApplicationUser

@{
    ViewBag.Title = "Details";
}

<div id="contentInner">
    <div class="row details">
        <div class="col-md-2"></div>
        <div class="col-md-3">
            <img src="/File?id=@Model.MyProfile.ID" alt="avatar" />
        </div>
        <div class="col-md-5">
            <table>
                <tr>
                    <td>Email:</td>
                    <td><h4>@Model.Email</h4></td>
                </tr>
                <tr>
                    <td>First Name:</td>
                    <td><h4>@Model.MyProfile.FirstName</h4></td>                        
                </tr>
                <tr>
                    <td>Last Name:</td>
                    <td><h4>@Model.MyProfile.LastName</h4></td>
                </tr>
            </table>
            <div class="row">
                <div class="col-md-2">
                    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-warning btn-fixed" })
                </div>
                <div class="col-md-2">
                    @using (Html.BeginForm("Delete", "Users", new { id = Model.Id })) {
                        @Html.AntiForgeryToken()
                        <input type="submit" value="Delete" class="btn btn-warning btn-fixed" />
                    }
                </div>
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>

</div>

Views/Users/Edit.cshtml
@model GymWebApp.Models.EditUserViewModel

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm("Edit", "Users", null, FormMethod.Post, new { enctype = "multipart/form-data" })) {
    @Html.AntiForgeryToken()

    <div id="contentInner" class="profile">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.ProfileId)

        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-3">
                <img src="/File?id=@Model.ProfileId" alt="avatar" />
            </div>
            <div class="col-md-5">
                <div class="form-group">
                    @Html.LabelFor(model => model.Email)
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.FirstName)
                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.LastName)
                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Avatar)
                    <input type="file" id="avatar" name="upload" accept="image/*" />
                </div>
                <div class="form-group">
                    <input type="submit" value="UPDATE" class="btn btn-warning form-control" />
                </div>
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Users/Index.cshtml
@model IEnumerable<GymWebApp.Models.ApplicationUser>

@{
    ViewBag.Title = "Index";
    string phrase = (string)ViewData["Phrase"];
}

<div id="contentInner">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
        @using (Html.BeginForm("Search", "Users", FormMethod.Get)) {
            <input type="text" name="phrase" value="@phrase" required />
            <input type="submit" value="Search" class="btn btn-default" />
        }
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th class="userEmail">MAIL</th>
                            <th class="userAction">ACTION</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model) {
                            <tr>
                                <td class="userEmail">@Html.DisplayFor(modelItem => item.Email)</td>
                                <td class="userAction">
                                    <div class="row">
                                        <div class="col-md-3">
                                            @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-default btn-fixed" })
                                        </div>
                                        <div class="col-md-3">
                                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-default btn-fixed" })
                                        </div>
                                        <div class="col-md-3">
                                            @using (Html.BeginForm("Delete", "Users", new { id = item.Id })) {
                                                @Html.AntiForgeryToken()
                                                <input type="submit" value="Delete" class="btn btn-default btn-fixed" />
                                            }
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>